openapi: 3.0.0
info:
  title: Seicho API
  description: API documentation for Seicho, the online diary application.
  version: 1.0.0
servers:
  - url: https://api.seicho.com/v1
    description: Production server

paths:
  /entries/{id}:
    $ref: './paths/diary.yaml'
  /signup:
    $ref: './paths/signup.yaml'
  /add-entry:
    $ref: './paths/add_diary_entry.yaml'

components:
  schemas:
    Diary:
      $ref: './components/schemas/diary.yaml'
    SignUp:
      $ref: './components/schemas/sign-up.yaml'
    DiaryEntry:
      allOf:
        - $ref: './components/schemas/diary.yaml'
        - $ref: './components/schemas/diary-shareable.yaml'
