openapi: 3.0.0
info:
  title: Seicho API
  description: API documentation for Seicho, the online diary application.
  version: 1.0.0
servers:
  - url: https://api.seicho.com/v1
    description: Production server

paths:
  /entries/{id}:
    $ref: './paths/diary.yaml'

components:
  schemas:
    Diary:
      $ref: './components/schemas/diary.yaml'
